/**
 * Type definitions for Express with CSRF middleware
 */

import 'express';

declare global {
  namespace Express {
    interface Request {
      /**
       * CSRF token generated by csurf middleware
       */
      csrfToken(): string;
    }
  }
}
